sudo: required

services:
 - docker

language: generic

before_script:
 - docker-compose build
 - docker-compose up
 - docker-compose run moviedb bundle exec rails db:test:prepare

script:
 - docker-compose run --rm moviedb bundle exec rake spec