
default: &default
  adapter: postgresql
  encoding: unicode
  #host: localhost
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: MovieDB_development


test:
  <<: *default
  database: MovieDB_test
