default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: MovieDB_development


test:
  <<: *default
  database: MovieDB_test

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: moviedb
  username: moviedb
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
